services:
  r-pr-db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER:-reviewer}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-12341}
      POSTGRES_DB: ${DB_NAME:-reviewer-pr-db}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5434}:5432"

volumes:
  db_data:
